# Import Required Libraries
Import the necessary libraries, including pandas and TensorFlow.

In [66]:
# Import the necessary libraries
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load and Prepare Data
Load the data from a CSV file and split it into input features and target variable.

In [103]:
# Load the data from the CSV file
data = pd.read_csv('../data/output.csv')
data

league  season  matchId  goalsFor  goalsAgainst  totalGoalsBeforeAvg  \
0        bl1    2004     1377         4             1             2.000000   
1        bl1    2004     1391         1             2             2.333333   
2        bl1    2004     1394         1             2             2.142857   
3        bl1    2004     1409         4             1             2.000000   
4        bl1    2004     1419         2             1             2.222222   
...      ...     ...      ...       ...           ...                  ...   
14943    bl3    2023    67996         1             2             1.100000   
14944    bl3    2023    69304         5             2             1.320000   
14945    bl3    2023    69933         0             4             1.482759   
14946    bl3    2023    67991         5             0             1.777778   
14947    bl3    2023    69922         1             1             1.571429   

       totalGoalsAgainstBeforeAvg  opponentTotalGoalsBeforeAvg  \
0                        1.000000                     1.800000   
1                        1.000000                     1.666667   
2                        1.142857                     1.571429   
3                        1.250000                     1.875000   
4                        1.222222                     1.888889   
...                           ...                          ...   
14943                    1.100000                     0.900000   
14944                    1.120000                     1.680000   
14945                    1.275862                     1.413793   
14946                    2.000000                     1.000000   
14947                    1.571429                     1.428571   

       opponentTotalGoalsAgainstBeforeAvg  
0                                1.600000  
1                                1.333333  
2                                1.285714  
3                                1.500000  
4                                0.777778  
...                                   ...  
14943                            1.500000  
14944                            1.520000  
14945                            1.517241  
14946                            1.111111  
14947                            1.535714  

[14948 rows x 9 columns]

In [104]:
#drop not usable columns
data = data.drop(['league', 'season', 'matchId'], axis=1)
data

goalsFor  goalsAgainst  totalGoalsBeforeAvg  \
0             4             1             2.000000   
1             1             2             2.333333   
2             1             2             2.142857   
3             4             1             2.000000   
4             2             1             2.222222   
...         ...           ...                  ...   
14943         1             2             1.100000   
14944         5             2             1.320000   
14945         0             4             1.482759   
14946         5             0             1.777778   
14947         1             1             1.571429   

       totalGoalsAgainstBeforeAvg  opponentTotalGoalsBeforeAvg  \
0                        1.000000                     1.800000   
1                        1.000000                     1.666667   
2                        1.142857                     1.571429   
3                        1.250000                     1.875000   
4                        1.222222                     1.888889   
...                           ...                          ...   
14943                    1.100000                     0.900000   
14944                    1.120000                     1.680000   
14945                    1.275862                     1.413793   
14946                    2.000000                     1.000000   
14947                    1.571429                     1.428571   

       opponentTotalGoalsAgainstBeforeAvg  
0                                1.600000  
1                                1.333333  
2                                1.285714  
3                                1.500000  
4                                0.777778  
...                                   ...  
14943                            1.500000  
14944                            1.520000  
14945                            1.517241  
14946                            1.111111  
14947                            1.535714  

[14948 rows x 6 columns]

In [105]:
# Split the data into input features and target variable
X = data.drop(['goalsFor', 'goalsAgainst'], axis=1)
y1 = data['goalsFor']
y2 = data['goalsAgainst']

In [106]:
X

totalGoalsBeforeAvg  totalGoalsAgainstBeforeAvg  \
0                 2.000000                    1.000000   
1                 2.333333                    1.000000   
2                 2.142857                    1.142857   
3                 2.000000                    1.250000   
4                 2.222222                    1.222222   
...                    ...                         ...   
14943             1.100000                    1.100000   
14944             1.320000                    1.120000   
14945             1.482759                    1.275862   
14946             1.777778                    2.000000   
14947             1.571429                    1.571429   

       opponentTotalGoalsBeforeAvg  opponentTotalGoalsAgainstBeforeAvg  
0                         1.800000                            1.600000  
1                         1.666667                            1.333333  
2                         1.571429                            1.285714  
3                         1.875000                            1.500000  
4                         1.888889                            0.777778  
...                            ...                                 ...  
14943                     0.900000                            1.500000  
14944                     1.680000                            1.520000  
14945                     1.413793                            1.517241  
14946                     1.000000                            1.111111  
14947                     1.428571                            1.535714  

[14948 rows x 4 columns]

In [107]:
import numpy as np
# Convert y to a numpy array with the appropriate shape
X = np.array(list(X.values))

# y to tensor
X = tf.convert_to_tensor(X)
X

<tf.Tensor: shape=(14948, 4), dtype=float64, numpy=
array([[2.        , 1.        , 1.8       , 1.6       ],
       [2.33333333, 1.        , 1.66666667, 1.33333333],
       [2.14285714, 1.14285714, 1.57142857, 1.28571429],
       ...,
       [1.48275862, 1.27586207, 1.4137931 , 1.51724138],
       [1.77777778, 2.        , 1.        , 1.11111111],
       [1.57142857, 1.57142857, 1.42857143, 1.53571429]])>

In [109]:
y1

0        4
1        1
2        1
3        4
4        2
        ..
14943    1
14944    5
14945    0
14946    5
14947    1
Name: goalsFor, Length: 14948, dtype: int64

In [124]:
# convert y1 into one-hot encoded vectors
y1_onehot = pd.get_dummies(y1)
y2_onehot = pd.get_dummies(y2)
y1_onehot

0      1      2      3      4      5      6      7      8
0      False  False  False  False   True  False  False  False  False
1      False   True  False  False  False  False  False  False  False
2      False   True  False  False  False  False  False  False  False
3      False  False  False  False   True  False  False  False  False
4      False  False   True  False  False  False  False  False  False
...      ...    ...    ...    ...    ...    ...    ...    ...    ...
14943  False   True  False  False  False  False  False  False  False
14944  False  False  False  False  False   True  False  False  False
14945   True  False  False  False  False  False  False  False  False
14946  False  False  False  False  False   True  False  False  False
14947  False   True  False  False  False  False  False  False  False

[14948 rows x 9 columns]

In [125]:
y2_onehot

0      1      2      3      4      5      6      7      8      9
0      False   True  False  False  False  False  False  False  False  False
1      False  False   True  False  False  False  False  False  False  False
2      False  False   True  False  False  False  False  False  False  False
3      False   True  False  False  False  False  False  False  False  False
4      False   True  False  False  False  False  False  False  False  False
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
14943  False  False   True  False  False  False  False  False  False  False
14944  False  False   True  False  False  False  False  False  False  False
14945  False  False  False  False   True  False  False  False  False  False
14946   True  False  False  False  False  False  False  False  False  False
14947  False   True  False  False  False  False  False  False  False  False

[14948 rows x 10 columns]

In [126]:
# append one column at the end of y1_onehot
y1_onehot['9'] = False
y1_onehot

0      1      2      3      4      5      6      7      8      9
0      False  False  False  False   True  False  False  False  False  False
1      False   True  False  False  False  False  False  False  False  False
2      False   True  False  False  False  False  False  False  False  False
3      False  False  False  False   True  False  False  False  False  False
4      False  False   True  False  False  False  False  False  False  False
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
14943  False   True  False  False  False  False  False  False  False  False
14944  False  False  False  False  False   True  False  False  False  False
14945   True  False  False  False  False  False  False  False  False  False
14946  False  False  False  False  False   True  False  False  False  False
14947  False   True  False  False  False  False  False  False  False  False

[14948 rows x 10 columns]

In [132]:
#convert y1 and y2 into tensors for the output layer
y1_out = tf.convert_to_tensor(y1_onehot)
y2_out = tf.convert_to_tensor(y2_onehot)
y1_out

<tf.Tensor: shape=(14948, 10), dtype=bool, numpy=
array([[False, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False],
       ...,
       [ True, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])>

In [133]:
y2_out

<tf.Tensor: shape=(14948, 10), dtype=bool, numpy=
array([[False,  True, False, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       [False, False,  True, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [ True, False, False, ..., False, False, False],
       [False,  True, False, ..., False, False, False]])>

# Define the Neural Network Model
Define a Sequential neural network model with Dense layers.

In [158]:
# Define the neural network model 
# with 1 input layer of 4 neurons, 
# 1 hidden layer and 64 neurons and 
# 1 output layer with 10 neurons and softmax activation function

model = Sequential([
    Dense(4, activation='relu', input_shape=(4,)),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')

])



# Compile the Model
Compile the model with binary cross-entropy loss, Adam optimizer, and accuracy metrics.

In [159]:
# Compile the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train the Model
Train the model using the fit() method with specified epochs and batch size.

In [160]:
# Train the model
model.fit(X, y1_out, epochs=10, batch_size=32)

Epoch 1/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 1s 759us/step - accuracy: 0.1781 - loss: 0.4086
Epoch 2/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - accuracy: 0.3270 - loss: 0.2418
Epoch 3/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - accuracy: 0.3269 - loss: 0.2409
Epoch 4/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 747us/step - accuracy: 0.3306 - loss: 0.2404
Epoch 5/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 739us/step - accuracy: 0.3275 - loss: 0.2407
Epoch 6/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 752us/step - accuracy: 0.3366 - loss: 0.2393
Epoch 7/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 733us/step - accuracy: 0.3386 - loss: 0.2389
Epoch 8/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - accuracy: 0.3322 - loss: 0.2389
Epoch 9/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 710us/step - accuracy: 0.3360 - loss: 0.2382
Epoch 10/10
468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 720us/step - accuracy: 0.3328 - loss: 0.2386


# Save the Trained Model
Save the trained model to a file using the save() method.

In [161]:
# Save the Trained Model

# Save the trained model to a file using the save() method
model.save('trained_model.h5')

In [162]:
# Load the Trained Model
saved_model = tf.keras.models.load_model('trained_model.h5')

In [163]:
# Use the model to make predictions
predictions = saved_model.predict(X)

468/468 ━━━━━━━━━━━━━━━━━━━━ 0s 658us/step


In [164]:
predictions.shape

(14948, 10)

In [169]:
# convert one-hot encoded predictions to the original format
y1_pred = np.argmax(predictions, axis=1)

In [170]:
y1_pred

array([1, 1, 1, ..., 1, 1, 1])